steps:
- name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/osix-training-auth/osixtrainingbackend:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/osix-training-auth/osixtrainingbackend:$SHORT_SHA']